language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - docker logout
  - echo "hejianqin0229" | docker login -u "ddsnake" --password-stdin
  - docker build -t ddsnake/yx-h5:latest .
  - docker push ddsnake/yx-h5:latest
